services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  api-gateway:
    container_name: gorgon-api-gateway
    build: api-gateway
    entrypoint: node main.js
    depends_on:
      - rabbitmq
    expose:
      - 8080:8080
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
  datastore:
    container_name: gorgon-datastore
    build: datastore
    entrypoint: node main.js
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - DATABASE_URI=mongodb://mongodb:27017
  orchestrator:
    container_name: gorgon-orchestrator
    build: orchestrator
    entrypoint: node main.js
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
