services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  api-gateway:
    container_name: gorgon-api-gateway
    build:
      context: api-gateway
    depends_on:
      - rabbitmq
    expose:
      - 8080:8080
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
  datastore:
    container_name: gorgon-datastore
    build:
      context: datastore
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
  orchestrator:
    container_name: gorgon-orchestrator
    build:
      context: orchestrator
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
